// rvtest_config.h for cv32a65x
#define RV_MODEL_PMP_GRAIN 0
#define RV_MODEL_NUM_PMPS 16
#define XLEN32

#define RAM_BASE_ADDR  0x80000000
#define LARGEST_PROGRAM 0X00010000

#define RVMODEL_ACCESS_FAULT_ADDRESS 0x00000000
#define CLINT_BASE 0x02000000

#define C_SUPPORTED
#define I_SUPPORTED
#define M_SUPPORTED
#define ZBA_SUPPORTED
#define ZBB_SUPPORTED
#define ZBS_SUPPORTED
#define ZCA_SUPPORTED
#define ZICSR_SUPPORTED

#define COUNTINHIBIT_EN_0
#define COUNTINHIBIT_EN_2
#define TIME_CSR_IMPLEMENTED
